namespace SizeBench.AnalysisEngine.DIAInterop;

internal enum DIAHRESULTs : uint
{
    E_PDB_USAGE = 0x806D0002,
    E_PDB_OUT_OF_MEMORY,
    E_PDB_FILE_SYSTEM,
    E_PDB_NOT_FOUND,
    E_PDB_INVALID_SIG,
    E_PDB_INVALID_AGE,
    E_PDB_PRECOMP_REQUIRED,
    E_PDB_OUT_OF_TI,
    E_PDB_NOT_IMPLEMENTED,
    E_PDB_V1_PDB,
    E_PDB_FORMAT,
    E_PDB_LIMIT,
    E_PDB_CORRUPT,
    E_PDB_TI16,
    E_PDB_ACCESS_DENIED,
    E_PDB_ILLEGAL_TYPE_EDIT,
    E_PDB_INVALID_EXECUTABLE,
    E_PDB_DBG_NOT_FOUND,
    E_PDB_NO_DEBUG_INFO,
    E_PDB_INVALID_EXE_TIMESTAMP,
    E_PDB_RESERVED,
    E_PDB_DEBUG_INFO_NOT_IN_PDB,
    E_PDB_SYMSRV_BAD_CACHE_PATH,
    E_PDB_SYMSRV_CACHE_FULL,
    E_PDB_OBJECT_DISPOSED,
    E_PDB_MAX, // Name is misleading, this is locked forever due to interop issues in DIA and COM, but there are more beyond it.
    E_PDB_IFC_RECORD_MISSING_DESIGNATOR,
    E_PDB_IFC_RECORD_MISSING_REFERENCE,
    E_PDB_IFC_FAILED_TO_LOAD,
    E_PDB_IFC_FAILED_TO_LOAD_MISMATCH_HASH,
    E_PDB_IFC_DEBUG_STREAM_FAILED_OPEN,
    E_PDB_IFC_DEBUG_STREAM_EMPTY,
    E_PDB_IFC_DEBUG_STREAM_HASH_MISMATCH,
    E_DIA_INPROLOG = 0x806D0064, // This is what all the bit shifting and ors in dia2.h resolve to
    E_DIA_SYNTAX,
    E_DIA_FRAME_ACCESS,
    E_DIA_VALUE,
    E_DIA_COFF_ACCESS = 0x806D00C8, // Again the result of the bit shifting and ors in dia2.h
    E_DIA_COMP_PDB_ACCESS,
}
